kind: Deployment
apiVersion: apps/v1
metadata:
  name: clusterlifecycle-state-metrics
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterlifecycle-state-metrics
  template:
    metadata:
      labels:
        app: clusterlifecycle-state-metrics
    spec:
      serviceAccountName: clusterlifecycle-state-metrics
      containers:
      - name: clusterlifecycle-state-metrics
        imagePullPolicy: IfNotPresent
        args:
          - "--http-port=8080"
          - "--http-telemetry-port=8081"
          - "--https-port=8443"
          - "--https-telemetry-port=8444"
          - "--tls-crt-file=/var/run/clusterlifecycle-state-metrics/tls.crt"
          - "--tls-key-file=/var/run/clusterlifecycle-state-metrics/tls.key"
        volumeMounts:
          - mountPath: "/var/run/clusterlifecycle-state-metrics"
            name: certs
            readOnly: true
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      volumes:
        - name: certs
          secret:
            secretName: clusterlifecycle-state-metrics